// flow-typed signature: 52a5d2d8c10985f4e5e44f2348cd7565
// flow-typed version: <<STUB>>/enzyme-wait_v^1.0.9/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-wait'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-wait' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'enzyme-wait/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'enzyme-wait/lib/index.js' {
  declare module.exports: $Exports<'enzyme-wait/lib/index'>;
}
