// flow-typed signature: 977e671cf01b8264379d71105cf81a2b
// flow-typed version: <<STUB>>/initializable-reducer_v^1.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'initializable-reducer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'initializable-reducer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'initializable-reducer/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'initializable-reducer/lib/index.js' {
  declare module.exports: $Exports<'initializable-reducer/lib/index'>;
}
